title: "Pre-Growth Environmental Stresses Affect Foodborne Pathogens Response to Subsequent Chemical Treatments"
authors: "A Singh, V Yemmireddy"
venue: "Microorganisms"
volume: "10"
issue: "4"
pages: "786"
year: 2022
type: "Journal article"
url: "https://www.mdpi.com/2076-2607/10/4/786"
